name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer, SDK, and NDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache
            ~/.buildozer/android/platform/android-sdk
            ~/.buildozer/android/platform/android-ndk
            # Add any custom directories where your binaries (ffmpeg, yt-dlp) are stored
            ~/.buildozer/android/app/code_cache
          key: Linux-buildozer-${{ runner.os }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            Linux-buildozer-${{ runner.os }}-

      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer -v android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
